### ISSUE TITLE
TP02: Build Your First App

### ISSUE THREAD

**Issue by fahritech04** [indraazimi/mobpro1-compose#1]
## 1. Tuliskan Composable function sederhana yang terdiri dari satu Tombol bertuliskan “Hitung +1” 
Jawab : 
```
............

@Composable
fun Counter() {
    // Menyimpan nilai counter dalam state yang mutable
    val count = remember { mutableStateOf(0) }

    // Menambahkan fungsi untuk menambah nilai counter
    fun onButtonClick() {
        count.value++
    }

    Column(
        modifier = Modifier
            .fillMaxWidth()
            .padding(16.dp),
        verticalArrangement = Arrangement.Center,
    ) {
        // Menampilkan teks dengan nilai counter
        Text(text = "Nilai counter: ${count.value}")

        // Menambahkan tombol dengan teks "Hitung +1" dan fungsi onButtonClick
        Button(onClick = onButtonClick) {
            Text(text = "Hitung +1")
        }
    }
}
```

## 2. Apa fungsi TopAppBar pada komponen Scaffold di aplikasi Android? 
Jawab :
TopAppBar adalah sebuah komponen di dalam Compose Material library yang digunakan untuk membuat bagian atas layar aplikasi Android. Komponen ini menyediakan beberapa fitur, seperti Menampilkan judul, Menambahkan tombol, Menentukan warna, Menambahkan ikon.

## 3. Apa yang dimaksud dengan state dan recomposition? 
Jawab :

**State** dalam Jetpack Compose adalah sebuah objek yang menyimpan data yang dapat berubah. Data ini dapat berupa nilai primitif, seperti string atau integer, atau objek kompleks, seperti daftar atau peta. State digunakan untuk melacak perubahan data dan memperbarui UI aplikasi.

**Recomposition** adalah proses di mana Jetpack Compose secara otomatis memperbarui UI aplikasi saat state berubah. Recomposition terjadi ketika:
- Nilai state diubah.
- Komposisi baru ditambahkan ke dalam hirarki komposisi.
- Komposisi dihapus dari hirarki komposisi.

## 4. Di Compose, terdapat 3 jenis container: Column, Row dan Box. Jelaskan kegunaan masing-masing! 
Jawab : 
**Column:**
- Kegunaan: Digunakan untuk menata elemen UI secara vertikal, satu di atas yang lain. Berguna untuk membuat daftar, menu, atau struktur hierarkis.
- Contoh: Bayangkan kita membuat daftar tugas. Setiap tugas akan menjadi elemen UI, dan Column akan menyusunnya secara vertikal dalam urutan.
- Pengaturan tambahan: Column menawarkan kontrol atas alignment horizontal elemen (misalnya, tengah, kiri, kanan) dan spacing antar elemen.

**Row:**
- Kegunaan: Digunakan untuk menata elemen UI secara horizontal, berdampingan. Berguna untuk membuat toolbar, tab bar, atau group elemen terkait secara horizontal.
- Contoh: Bayangkan kita membuat toolbar dengan tombol "Tambah", "Edit", dan "Hapus". Row akan menempatkan tombol-tombol ini berdampingan dalam satu baris.
- Pengaturan tambahan: Row juga menawarkan kontrol atas alignment vertikal elemen (misalnya, atas, tengah, bawah) dan spacing antar elemen.

**Box:**
- Kegunaan: Digunakan untuk menempatkan elemen UI secara tumpang tindih di posisi tertentu. Berguna untuk membuat layout yang lebih kompleks, di mana Anda ingin elemen saling tumpang tindih atau diposisikan secara absolut.
- Contoh: Bayangkan kita membuat overlay transparan di atas gambar untuk menampilkan teks informasi. Box memungkinkan Anda menempatkan teks tepat di atas gambar dengan transparansi yang diinginkan.
- Pengaturan tambahan: Box menawarkan kontrol atas ukuran, posisi, dan padding elemen yang ditempatkan di dalamnya.

## 5. Bagaimana cara kita mendukung lebih dari satu bahasa di aplikasi Android? 
Jawab :
- Di perangkat Android, buka aplikasi Setelan.
- Ketuk Sistem. Bahasa & input. Bahasa.
- Tambahkan bahasa sebagai bahasa sekunder.
- Setelah beberapa menit, buka kembali aplikasi Setelan.
- Ketuk Sistem. Bahasa & input. Bahasa Aplikasi.
- Pilih aplikasi yang ingin diubah.
- Pilih bahasa.

**Comment by indraazimi** [comment]
@fahritech04 ngerjain TP itu di repo praktikum yang link nya dari dosen kelas.. Bukan di repo sini karena tidak akan dinilai.

**Comment by fahritech04** [comment]
Siap pak, terima kasih banyak pak. Mohon Maaf saya sebelumnya pak 🙏
