### ISSUE TITLE
TP07: Scrollable List

### ISSUE THREAD

**Issue by Gusdio36** [indraazimi/mobpro1-compose#2]
Ada beberapa alasan mengapa tampilan list yang baik haruslah konsisten untuk setiap item dan diurutkan berdasarkan kriteria tertentu:
-> Urutan yang logis berdasarkan kriteria tertentu (seperti nama, tanggal, atau kategori) memudahkan pengguna menemukan informasi yang dicari tanpa harus membaca seluruh list.
-> List yang konsisten dan teratur terlihat lebih profesional dan rapi.
Hal ini meningkatkan kredibilitas informasi yang disajikan dan membuat pengguna lebih nyaman untuk menggunakan list tersebut.
-> Konsistensi dalam format item (seperti font, ukuran, warna, dan tata letak) membantu pengguna menyortir list dengan mudah dan cepat memahami informasi yang disajikan.

Menampilkan data berupa list menggunakan LazyColumn akan lebih efisien karena, LazyColumn adalah cara yang lebih efisien untuk menampilkan data dalam bentuk list. LazyColumn meminimalkan penggunaan memori, meningkatkan scroll performance, dan mendukung data yang besar.

Toast:

Kasus: Memberi tahu pengguna bahwa akun mereka telah berhasil diperbarui.
Pesan: "Akun Anda telah berhasil diperbarui!"

Snackbar:

Kasus: Memberi tahu pengguna bahwa pesan mereka telah terkirim.
Pesan: "Pesan Anda telah terkirim!"

Banner:

Kasus: Memberi tahu pengguna tentang penawaran khusus di aplikasi.
Pesan: "Dapatkan diskon 20% untuk semua produk!"

Dialog:

Kasus: Meminta konfirmasi dari pengguna sebelum menghapus data.
Pesan: "Apakah Anda yakin ingin menghapus data ini?"
Pilihan: "Ya" dan "Tidak"

Data Layer:

Menyimpan data aplikasi, seperti data pengguna, pengaturan, dan data yang diambil dari server.
Dapat menggunakan berbagai sumber data, seperti SQLite, Room Database, atau Firebase.

UI Layer:

Bertanggung jawab untuk menampilkan antarmuka pengguna aplikasi.
Terdiri dari elemen UI seperti TextView, Button, dan RecyclerView.
Dikelola oleh ViewModels dan Compose.

Lapisan ViewModel:

Menghubungkan Lapisan UI dengan Lapisan Data.
Mengelola data dan logika aplikasi.
Memberikan data yang diolah ke UI.

Komponen Lainnya:

Events: Digunakan untuk mengkomunikasikan tindakan pengguna dari Lapisan UI ke ViewModel.
State: Menyimpan data yang berubah-ubah dalam aplikasi.
Ul elements: Elemen UI individual yang membentuk antarmuka aplikasi.

Berikan informasi yang jelas dan ringkas kepada pengguna tentang mengapa list kosong. Contohnya:

-> "Belum ada data."
-> "Data tidak ditemukan."

berikan solusi kepada pengguna agar mereka dapat mengisi list. Contohnya:

-> "Tambahkan data baru dengan menekan tombol ini."
-> "Cari data yang Anda inginkan dengan menekan tombol ini."

**Comment by indraazimi** [comment]
TP ngerjainnya di repo praktikum masing2, bukan di sini.
